apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spredning
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spredning.intern.dev.nav.no
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: 9046ac9d-bb00-47dc-bcfb-e5221bf8d7f9 # tbd
    sidecar:
      enabled: true
  env:
    - name: DOKARKIV_URL
      value: https://dokarkiv-q2.dev-fss-pub.nais.io
    - name: DOKARKIV_TARGET
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
    - name: DOKDISTFORDELING_URL
      value: https://dokdistfordeling.dev-fss-pub.nais.io
    - name: DOKDISTFORDELING_TARGET
      value: api://dev-fss.teamdokumenthandtering.dokdistfordeling/.default
  accessPolicy:
    outbound:
      rules:
        - application: dokarkiv
          namespace: teamdokumenthandtering
          cluster: dev-fss
        - application: dokdistfordeling
          namespace: teamdokumenthandtering
          cluster: dev-fss
